services:
  backend:
    build: ./backend  # Ruta donde está tu Dockerfile de Django
    ports:
      - "###:###"  # Expone el puerto de Django (o cambia a 80 o 443 para producción)
    depends_on:
      - db  # Asegúrate de que la base de datos esté lista antes de iniciar el backend
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust  # Solo para desarrollo, ajusta esto en producción
    env_file:
      - ./backend/.env  # Si tienes variables de entorno

  frontend:
    build: ./frontend  # Ruta donde está tu Dockerfile de React/Vite
    ports:
      - "###:###"  # Expone el puerto de Vite (o cambia a 80 o 443 para producción)
    stdin_open: false  # Eliminar para producción
    tty: false  # Eliminar para producción

  db:
    image: postgres:17
    environment:
      POSTGRES_DB: ###
      POSTGRES_USER: ###
      POSTGRES_PASSWORD: ###
    command: postgres -c listen_addresses='*'  # Aceptar conexiones de cualquier IP (ajustar en producción)
    ports:
      - "###:###"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
