# Generated by Django 5.2 on 2025-04-12 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartitem',
            options={'verbose_name': 'Item de Carrito', 'verbose_name_plural': 'Items de Carrito'},
        ),
    ]
